rssSuccess:
  http_metas:
    content-type: text/xml

  metas:
    title:        Diem Project Blog
    language:     en
    robots:       index, follow

  stylesheets:    [-*]

  javascripts:    [-*]

  has_layout:     false