generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: CommunityArticle
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: community_article
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - author
          - href
          - is_active
          - language
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - title
          - is_active
          - author
          - href
          - language
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Others: [author, href, language]
        class: CommunityArticleAdminForm
        fields:
          href: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
      edit: ~
      new: ~
