generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Site
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: site
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_fr:
          label: Fr
        is_active:
          label: Active
      list:
        display:
          - '=name'
          - screen
          - text
          - url
          - diem_version
          - is_fr
          - is_active
          - _created_at
          - _updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - name
          - is_fr
          - is_active
          - text
          - url
          - screen
          - diem_version
          - created_at
          - updated_at
      form:
        display:
          NONE: [name, is_fr, is_active]
          Screen: [screen_form, screen_view]
          Text: [text]
          Others: [url, diem_version]
        class: SiteAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: true
